---
- hosts: dc
  roles:
    - dc
    - common
  tags: dc

- hosts: wef
  roles:
    - wef
    - common
    - sentinel # Added role for Sentinel
  tags: wef

- hosts: win10
  roles:
    - win10
    - common
  tags: win10

- hosts: exchange
  roles:
    - exchange
    - common
  tags: exchange